<?php
$fa_icons = array(
        ''                              => '',
        'fa-angellist'                  => 'fa-angellist',
        'fa-area-chart'                 => 'fa-area-chart',
        'fa-at'                         => 'fa-at',
        'fa-bell-slash'                 => 'fa-bell-slash',
        'fa-bell-slash-o'               => 'fa-bell-slash-o',
        'fa-bicycle'                    => 'fa-bicycle',
        'fa-binoculars'                 => 'fa-binoculars',
        'fa-birthday-cake'              => 'fa-birthday-cake',
        'fa-bus'                        => 'fa-bus',
        'fa-calculator'                 => 'fa-calculator',
        'fa-cc'                         => 'fa-cc',
        'fa-cc-amex'                    => 'fa-cc-amex',
        'fa-cc-discover'                => 'fa-cc-discover',
        'fa-cc-mastercard'              => 'fa-cc-mastercard',
        'fa-cc-paypal'                  => 'fa-cc-paypal',
        'fa-cc-stripe'                  => 'fa-cc-stripe',
        'fa-cc-visa'                    => 'fa-cc-visa',
        'fa-copyright'                  => 'fa-copyright',
        'fa-eyedropper'                 => 'fa-eyedropper',
        'fa-futbol-o'                   => 'fa-futbol-o',
        'fa-google-wallet'              => 'fa-google-wallet',
        'fa-ils'                        => 'fa-ils',
        'fa-ioxhost'                    => 'fa-ioxhost',
        'fa-lastfm'                     => 'fa-lastfm',
        'fa-lastfm-square'              => 'fa-lastfm-square',
        'fa-line-chart'                 => 'fa-line-chart',
        'fa-meanpath'                   => 'fa-meanpath',
        'fa-newspaper-o'                => 'fa-newspaper-o',
        'fa-paint-brush'                => 'fa-paint-brush',
        'fa-paypal'                     => 'fa-paypal',
        'fa-pie-chart'                  => 'fa-pie-chart',
        'fa-plug'                       => 'fa-plug',
        'fa-shekel'                     => 'fa-shekel',
        'fa-sheqel'                     => 'fa-sheqel',
        'fa-slideshare'                 => 'fa-slideshare',
        'fa-soccer-ball-o'              => 'fa-soccer-ball-o',
        'fa-toggle-off'                 => 'fa-toggle-off',
        'fa-toggle-on'                  => 'fa-toggle-on',
        'fa-trash'                      => 'fa-trash',
        'fa-tty'                        => 'fa-tty',
        'fa-twitch'                     => 'fa-twitch',
        'fa-wifi'                       => 'fa-wifi',
        'fa-yelp'                       => 'fa-yelp',
        'fa-adjust'                     => 'fa-adjust',
        'fa-anchor'                     => 'fa-anchor',
        'fa-archive'                    => 'fa-archive',
        'fa-arrows'                     => 'fa-arrows',
        'fa-arrows-h'                   => 'fa-arrows-h',
        'fa-arrows-v'                   => 'fa-arrows-v',
        'fa-asterisk'                   => 'fa-asterisk',
        'fa-automobile'                 => 'fa-automobile',
        'fa-ban'                        => 'fa-ban',
        'fa-bank'                       => 'fa-bank',
        'fa-bar-chart'                  => 'fa-bar-chart',
        'fa-bar-chart-o'                => 'fa-bar-chart-o',
        'fa-barcode'                    => 'fa-barcode',
        'fa-bars'                       => 'fa-bars',
        'fa-beer'                       => 'fa-beer',
        'fa-bell'                       => 'fa-bell',
        'fa-bell-o'                     => 'fa-bell-o',
        'fa-bolt'                       => 'fa-bolt',
        'fa-bomb'                       => 'fa-bomb',
        'fa-book'                       => 'fa-book',
        'fa-bookmark'                   => 'fa-bookmark',
        'fa-bookmark-o'                 => 'fa-bookmark-o',
        'fa-briefcase'                  => 'fa-briefcase',
        'fa-bug'                        => 'fa-bug',
        'fa-building'                   => 'fa-building',
        'fa-building-o'                 => 'fa-building-o',
        'fa-bullhorn'                   => 'fa-bullhorn',
        'fa-bullseye'                   => 'fa-bullseye',
        'fa-cab'                        => 'fa-cab',
        'fa-calendar'                   => 'fa-calendar',
        'fa-calendar-o'                 => 'fa-calendar-o',
        'fa-camera'                     => 'fa-camera',
        'fa-camera-retro'               => 'fa-camera-retro',
        'fa-car'                        => 'fa-car',
        'fa-caret-square-o-down'        => 'fa-caret-square-o-down',
        'fa-caret-square-o-left'        => 'fa-caret-square-o-left',
        'fa-caret-square-o-right'       => 'fa-caret-square-o-right',
        'fa-caret-square-o-up'          => 'fa-caret-square-o-up',
        'fa-certificate'                => 'fa-certificate',
        'fa-check'                      => 'fa-check',
        'fa-check-circle'               => 'fa-check-circle',
        'fa-check-circle-o'             => 'fa-check-circle-o',
        'fa-check-square'               => 'fa-check-square',
        'fa-check-square-o'             => 'fa-check-square-o',
        'fa-child'                      => 'fa-child',
        'fa-circle'                     => 'fa-circle',
        'fa-circle-o'                   => 'fa-circle-o',
        'fa-circle-o-notch'             => 'fa-circle-o-notch',
        'fa-circle-thin'                => 'fa-circle-thin',
        'fa-clock-o'                    => 'fa-clock-o',
        'fa-close'                      => 'fa-close',
        'fa-cloud'                      => 'fa-cloud',
        'fa-cloud-download'             => 'fa-cloud-download',
        'fa-cloud-upload'               => 'fa-cloud-upload',
        'fa-code'                       => 'fa-code',
        'fa-code-fork'                  => 'fa-code-fork',
        'fa-coffee'                     => 'fa-coffee',
        'fa-cog'                        => 'fa-cog',
        'fa-cogs'                       => 'fa-cogs',
        'fa-comment'                    => 'fa-comment',
        'fa-comment-o'                  => 'fa-comment-o',
        'fa-comments'                   => 'fa-comments',
        'fa-comments-o'                 => 'fa-comments-o',
        'fa-compass'                    => 'fa-compass',
        'fa-credit-card'                => 'fa-credit-card',
        'fa-crop'                       => 'fa-crop',
        'fa-crosshairs'                 => 'fa-crosshairs',
        'fa-cube'                       => 'fa-cube',
        'fa-cubes'                      => 'fa-cubes',
        'fa-cutlery'                    => 'fa-cutlery',
        'fa-dashboard'                  => 'fa-dashboard',
        'fa-database' => 'fa-database',
        'fa-desktop' => 'fa-desktop',
        'fa-dot-circle-o' => 'fa-dot-circle-o',
        'fa-download' => 'fa-download',
        'fa-edit' => 'fa-edit',
        'fa-ellipsis-h' => 'fa-ellipsis-h',
        'fa-ellipsis-v' => 'fa-ellipsis-v',
        'fa-envelope' => 'fa-envelope',
        'fa-envelope-o' => 'fa-envelope-o',
        'fa-envelope-square' => 'fa-envelope-square',
        'fa-eraser' => 'fa-eraser',
        'fa-exchange' => 'fa-exchange',
        'fa-exclamation' => 'fa-exclamation',
        'fa-exclamation-circle' => 'fa-exclamation-circle',
        'fa-exclamation-triangle' => 'fa-exclamation-triangle',
        'fa-external-link' => 'fa-external-link',
        'fa-external-link-square' => 'fa-external-link-square',
        'fa-eye' => 'fa-eye',
        'fa-eye-slash' => 'fa-eye-slash',
        'fa-fax' => 'fa-fax',
        'fa-female' => 'fa-female',
        'fa-fighter-jet' => 'fa-fighter-jet',
        'fa-file-archive-o' => 'fa-file-archive-o',
        'fa-file-audio-o' => 'fa-file-audio-o',
        'fa-file-code-o' => 'fa-file-code-o',
        'fa-file-excel-o' => 'fa-file-excel-o',
        'fa-file-image-o' => 'fa-file-image-o',
        'fa-file-movie-o' => 'fa-file-movie-o',
        'fa-file-pdf-o' => 'fa-file-pdf-o',
        'fa-file-photo-o' => 'fa-file-photo-o',
        'fa-file-picture-o' => 'fa-file-picture-o',
        'fa-file-powerpoint-o' => 'fa-file-powerpoint-o',
        'fa-file-sound-o' => 'fa-file-sound-o',
        'fa-file-video-o' => 'fa-file-video-o',
        'fa-file-word-o' => 'fa-file-word-o',
        'fa-file-zip-o' => 'fa-file-zip-o',
        'fa-film' => 'fa-film',
        'fa-filter' => 'fa-filter',
        'fa-fire' => 'fa-fire',
        'fa-fire-extinguisher' => 'fa-fire-extinguisher',
        'fa-flag' => 'fa-flag',
        'fa-flag-checkered' => 'fa-flag-checkered',
        'fa-flag-o' => 'fa-flag-o',
        'fa-flash' => 'fa-flash',
        'fa-flask' => 'fa-flask',
        'fa-folder' => 'fa-folder',
        'fa-folder-o' => 'fa-folder-o',
        'fa-folder-open' => 'fa-folder-open',
        'fa-folder-open-o' => 'fa-folder-open-o',
        'fa-frown-o' => 'fa-frown-o',
        'fa-gamepad' => 'fa-gamepad',
        'fa-gavel' => 'fa-gavel',
        'fa-gear' => 'fa-gear',
        'fa-gears' => 'fa-gears',
        'fa-gift' => 'fa-gift',
        'fa-glass' => 'fa-glass',
        'fa-globe' => 'fa-globe',
        'fa-graduation-cap' => 'fa-graduation-cap',
        'fa-group' => 'fa-group',
        'fa-hdd-o' => 'fa-hdd-o',
        'fa-headphones' => 'fa-headphones',
        'fa-heart' => 'fa-heart',
        'fa-heart-o' => 'fa-heart-o',
        'fa-history' => 'fa-history',
        'fa-home' => 'fa-home',
        'fa-image' => 'fa-image',
        'fa-inbox' => 'fa-inbox',
        'fa-info' => 'fa-info',
        'fa-info-circle' => 'fa-info-circle',
        'fa-institution' => 'fa-institution',
        'fa-key' => 'fa-key',
        'fa-keyboard-o' => 'fa-keyboard-o',
        'fa-language' => 'fa-language',
        'fa-laptop' => 'fa-laptop',
        'fa-leaf' => 'fa-leaf',
        'fa-legal' => 'fa-legal',
        'fa-lemon-o' => 'fa-lemon-o',
        'fa-level-down' => 'fa-level-down',
        'fa-level-up' => 'fa-level-up',
        'fa-life-bouy' => 'fa-life-bouy',
        'fa-life-buoy' => 'fa-life-buoy',
        'fa-life-ring' => 'fa-life-ring',
        'fa-life-saver' => 'fa-life-saver',
        'fa-lightbulb-o' => 'fa-lightbulb-o',
        'fa-location-arrow' => 'fa-location-arrow',
        'fa-lock' => 'fa-lock',
        'fa-magic' => 'fa-magic',
        'fa-magnet' => 'fa-magnet',
        'fa-mail-forward' => 'fa-mail-forward',
        'fa-mail-reply' => 'fa-mail-reply',
        'fa-mail-reply-all' => 'fa-mail-reply-all',
        'fa-male' => 'fa-male',
        'fa-map-marker' => 'fa-map-marker',
        'fa-meh-o' => 'fa-meh-o',
        'fa-microphone' => 'fa-microphone',
        'fa-microphone-slash' => 'fa-microphone-slash',
        'fa-minus' => 'fa-minus',
        'fa-minus-circle' => 'fa-minus-circle',
        'fa-minus-square' => 'fa-minus-square',
        'fa-minus-square-o' => 'fa-minus-square-o',
        'fa-mobile' => 'fa-mobile',
        'fa-mobile-phone' => 'fa-mobile-phone',
        'fa-money' => 'fa-money',
        'fa-moon-o' => 'fa-moon-o',
        'fa-mortar-board' => 'fa-mortar-board',
        'fa-music' => 'fa-music',
        'fa-navicon' => 'fa-navicon',
        'fa-paper-plane' => 'fa-paper-plane',
        'fa-paper-plane-o' => 'fa-paper-plane-o',
        'fa-paw' => 'fa-paw',
        'fa-pencil' => 'fa-pencil',
        'fa-pencil-square' => 'fa-pencil-square',
        'fa-pencil-square-o' => 'fa-pencil-square-o',
        'fa-phone' => 'fa-phone',
        'fa-phone-square' => 'fa-phone-square',
        'fa-photo' => 'fa-photo',
        'fa-picture-o' => 'fa-picture-o',
        'fa-plane' => 'fa-plane',
        'fa-plus' => 'fa-plus',
        'fa-plus-circle' => 'fa-plus-circle',
        'fa-plus-square' => 'fa-plus-square',
        'fa-plus-square-o' => 'fa-plus-square-o',
        'fa-power-off' => 'fa-power-off',
        'fa-print' => 'fa-print',
        'fa-puzzle-piece' => 'fa-puzzle-piece',
        'fa-qrcode' => 'fa-qrcode',
        'fa-question' => 'fa-question',
        'fa-question-circle' => 'fa-question-circle',
        'fa-quote-left' => 'fa-quote-left',
        'fa-quote-right' => 'fa-quote-right',
        'fa-random' => 'fa-random',
        'fa-recycle' => 'fa-recycle',
        'fa-refresh' => 'fa-refresh',
        'fa-remove' => 'fa-remove',
        'fa-reorder' => 'fa-reorder',
        'fa-reply' => 'fa-reply',
        'fa-reply-all' => 'fa-reply-all',
        'fa-retweet' => 'fa-retweet',
        'fa-road' => 'fa-road',
        'fa-rocket' => 'fa-rocket',
        'fa-rss' => 'fa-rss',
        'fa-rss-square' => 'fa-rss-square',
        'fa-search' => 'fa-search',
        'fa-search-minus' => 'fa-search-minus',
        'fa-search-plus' => 'fa-search-plus',
        'fa-send' => 'fa-send',
        'fa-send-o' => 'fa-send-o',
        'fa-share' => 'fa-share',
        'fa-share-alt' => 'fa-share-alt',
        'fa-share-alt-square' => 'fa-share-alt-square',
        'fa-share-square' => 'fa-share-square',
        'fa-share-square-o' => 'fa-share-square-o',
        'fa-shield' => 'fa-shield',
        'fa-shopping-cart' => 'fa-shopping-cart',
        'fa-sign-in' => 'fa-sign-in',
        'fa-sign-out' => 'fa-sign-out',
        'fa-signal' => 'fa-signal',
        'fa-sitemap' => 'fa-sitemap',
        'fa-sliders' => 'fa-sliders',
        'fa-smile-o' => 'fa-smile-o',
        'fa-sort' => 'fa-sort',
        'fa-sort-alpha-asc' => 'fa-sort-alpha-asc',
        'fa-sort-alpha-desc' => 'fa-sort-alpha-desc',
        'fa-sort-amount-asc' => 'fa-sort-amount-asc',
        'fa-sort-amount-desc' => 'fa-sort-amount-desc',
        'fa-sort-asc' => 'fa-sort-asc',
        'fa-sort-desc' => 'fa-sort-desc',
        'fa-sort-down' => 'fa-sort-down',
        'fa-sort-numeric-asc' => 'fa-sort-numeric-asc',
        'fa-sort-numeric-desc' => 'fa-sort-numeric-desc',
        'fa-sort-up' => 'fa-sort-up',
        'fa-space-shuttle' => 'fa-space-shuttle',
        'fa-spinner' => 'fa-spinner',
        'fa-spoon' => 'fa-spoon',
        'fa-square' => 'fa-square',
        'fa-square-o' => 'fa-square-o',
        'fa-star' => 'fa-star',
        'fa-star-half' => 'fa-star-half',
        'fa-star-half-empty' => 'fa-star-half-empty',
        'fa-star-half-full' => 'fa-star-half-full',
        'fa-star-half-o' => 'fa-star-half-o',
        'fa-star-o' => 'fa-star-o',
        'fa-suitcase' => 'fa-suitcase',
        'fa-sun-o' => 'fa-sun-o',
        'fa-support' => 'fa-support',
        'fa-tablet' => 'fa-tablet',
        'fa-tachometer' => 'fa-tachometer',
        'fa-tag' => 'fa-tag',
        'fa-tags' => 'fa-tags',
        'fa-tasks' => 'fa-tasks',
        'fa-taxi' => 'fa-taxi',
        'fa-terminal' => 'fa-terminal',
        'fa-thumb-tack' => 'fa-thumb-tack',
        'fa-thumbs-down' => 'fa-thumbs-down',
        'fa-thumbs-o-down' => 'fa-thumbs-o-down',
        'fa-thumbs-o-up' => 'fa-thumbs-o-up',
        'fa-thumbs-up' => 'fa-thumbs-up',
        'fa-ticket' => 'fa-ticket',
        'fa-times' => 'fa-times',
        'fa-times-circle' => 'fa-times-circle',
        'fa-times-circle-o' => 'fa-times-circle-o',
        'fa-tint' => 'fa-tint',
        'fa-toggle-down' => 'fa-toggle-down',
        'fa-toggle-left' => 'fa-toggle-left',
        'fa-toggle-right' => 'fa-toggle-right',
        'fa-toggle-up' => 'fa-toggle-up',
        'fa-trash-o' => 'fa-trash-o',
        'fa-tree' => 'fa-tree',
        'fa-trophy' => 'fa-trophy',
        'fa-truck' => 'fa-truck',
        'fa-umbrella' => 'fa-umbrella',
        'fa-university' => 'fa-university',
        'fa-unlock' => 'fa-unlock',
        'fa-unlock-alt' => 'fa-unlock-alt',
        'fa-unsorted' => 'fa-unsorted',
        'fa-upload' => 'fa-upload',
        'fa-user' => 'fa-user',
        'fa-users' => 'fa-users',
        'fa-video-camera' => 'fa-video-camera',
        'fa-volume-down' => 'fa-volume-down',
        'fa-volume-off' => 'fa-volume-off',
        'fa-volume-up' => 'fa-volume-up',
        'fa-warning' => 'fa-warning',
        'fa-wheelchair' => 'fa-wheelchair',
        'fa-wrench' => 'fa-wrench',
        'fa-file' => 'fa-file',
        'fa-file-o' => 'fa-file-o',
        'fa-file-text' => 'fa-file-text',
        'fa-file-text-o' => 'fa-file-text-o',
        'fa-bitcoin' => 'fa-bitcoin',
        'fa-btc' => 'fa-btc',
        'fa-cny' => 'fa-cny',
        'fa-dollar' => 'fa-dollar',
        'fa-eur' => 'fa-eur',
        'fa-euro' => 'fa-euro',
        'fa-gbp' => 'fa-gbp',
        'fa-inr' => 'fa-inr',
        'fa-jpy' => 'fa-jpy',
        'fa-krw' => 'fa-krw',
        'fa-rmb' => 'fa-rmb',
        'fa-rouble' => 'fa-rouble',
        'fa-rub' => 'fa-rub',
        'fa-ruble' => 'fa-ruble',
        'fa-rupee' => 'fa-rupee',
        'fa-try' => 'fa-try',
        'fa-turkish-lira' => 'fa-turkish-lira',
        'fa-usd' => 'fa-usd',
        'fa-won' => 'fa-won',
        'fa-yen' => 'fa-yen',
        'fa-align-center' => ' fa-align-center',
        'fa-align-justify' => 'fa-align-justify',
        'fa-align-left' => 'fa-align-left',
        'fa-align-right' => 'fa-align-right',
        'fa-bold' => 'fa-bold',
        'fa-chain' => 'fa-chain',
        'fa-chain-broken' => 'fa-chain-broken',
        'fa-clipboard' => 'fa-clipboard',
        'fa-columns' => 'fa-columns',
        'fa-copy' => 'fa-copy',
        'fa-cut' => 'fa-cut',
        'fa-dedent' => 'fa-dedent',
        'fa-files-o' => 'fa-files-o',
        'fa-floppy-o' => 'fa-floppy-o',
        'fa-font' => 'fa-font',
        'fa-header' => 'fa-header',
        'fa-indent' => 'fa-indent',
        'fa-italic' => 'fa-italic',
        'fa-link' => 'fa-link',
        'fa-list' => 'fa-list',
        'fa-list-alt' => 'fa-list-alt',
        'fa-list-ol' => 'fa-list-ol',
        'fa-list-ul' => 'fa-list-ul',
        'fa-outdent' => 'fa-outdent',
        'fa-paperclip' => 'fa-paperclip',
        'fa-paragraph' => 'fa-paragraph',
        'fa-paste' => 'fa-paste',
        'fa-repeat' => 'fa-repeat',
        'fa-rotate-left' => 'fa-rotate-left',
        'fa-rotate-right' => 'fa-rotate-right',
        'fa-save' => 'fa-save',
        'fa-scissors' => 'fa-scissors',
        'fa-strikethrough' => 'fa-strikethrough',
        'fa-subscript' => 'fa-subscript',
        'fa-superscript' => 'fa-superscript',
        'fa-table' => 'fa-table',
        'fa-text-height' => 'fa-text-height',
        'fa-text-width' => 'fa-text-width',
        'fa-th' => 'fa-th',
        'fa-th-large' => 'fa-th-large',
        'fa-th-list' => 'fa-th-list',
        'fa-underline' => 'fa-underline',
        'fa-undo' => 'fa-undo',
        'fa-unlink' => 'fa-unlink',
        'fa-angle-double-down' => ' fa-angle-double-down',
        'fa-angle-double-left' => 'fa-angle-double-left',
        'fa-angle-double-right' => 'fa-angle-double-right',
        'fa-angle-double-up' => 'fa-angle-double-up',
        'fa-angle-down' => 'fa-angle-down',
        'fa-angle-left' => 'fa-angle-left',
        'fa-angle-right' => 'fa-angle-right',
        'fa-angle-up' => 'fa-angle-up',
        'fa-arrow-circle-down' => 'fa-arrow-circle-down',
        'fa-arrow-circle-left' => 'fa-arrow-circle-left',
        'fa-arrow-circle-o-down' => 'fa-arrow-circle-o-down',
        'fa-arrow-circle-o-left' => 'fa-arrow-circle-o-left',
        'fa-arrow-circle-o-right' => 'fa-arrow-circle-o-right',
        'fa-arrow-circle-o-up' => 'fa-arrow-circle-o-up',
        'fa-arrow-circle-right' => 'fa-arrow-circle-right',
        'fa-arrow-circle-up' => 'fa-arrow-circle-up',
        'fa-arrow-down' => 'fa-arrow-down',
        'fa-arrow-left' => 'fa-arrow-left',
        'fa-arrow-right' => 'fa-arrow-right',
        'fa-arrow-up' => 'fa-arrow-up',
        'fa-arrows-alt' => 'fa-arrows-alt',
        'fa-caret-down' => 'fa-caret-down',
        'fa-caret-left' => 'fa-caret-left',
        'fa-caret-right' => 'fa-caret-right',
        'fa-caret-up' => 'fa-caret-up',
        'fa-chevron-circle-down' => 'fa-chevron-circle-down',
        'fa-chevron-circle-left' => 'fa-chevron-circle-left',
        'fa-chevron-circle-right' => 'fa-chevron-circle-right',
        'fa-chevron-circle-up' => 'fa-chevron-circle-up',
        'fa-chevron-down' => 'fa-chevron-down',
        'fa-chevron-left' => 'fa-chevron-left',
        'fa-chevron-right' => 'fa-chevron-right',
        'fa-chevron-up' => 'fa-chevron-up',
        'fa-hand-o-down' => 'fa-hand-o-down',
        'fa-hand-o-left' => 'fa-hand-o-left',
        'fa-hand-o-right' => 'fa-hand-o-right',
        'fa-hand-o-up' => 'fa-hand-o-up',
        'fa-long-arrow-down' => 'fa-long-arrow-down',
        'fa-long-arrow-left' => 'fa-long-arrow-left',
        'fa-long-arrow-right' => 'fa-long-arrow-right',
        'fa-long-arrow-up' => 'fa-long-arrow-up',
        'fa-backward' => 'fa-backward',
        'fa-compress' => 'fa-compress',
        'fa-eject' => 'fa-eject',
        'fa-expand' => 'fa-expand',
        'fa-fast-backward' => 'fa-fast-backward',
        'fa-fast-forward' => 'fa-fast-forward',
        'fa-forward' => 'fa-forward',
        'fa-pause' => 'fa-pause',
        'fa-play' => 'fa-play',
        'fa-play-circle' => 'fa-play-circle',
        'fa-play-circle-o' => 'fa-play-circle-o',
        'fa-step-backward' => 'fa-step-backward',
        'fa-step-forward' => 'fa-step-forward',
        'fa-stop' => 'fa-stop',
        'fa-youtube-play' => 'fa-youtube-play'
    );
class travelogue_Shortcode_Manager {

	public $shortcodes;	

	public function delete_shortcode( $shortcode_name ) {
		unset( $this->$shortcodes[$shortcode_name] );
	}

}

$av_sm = new travelogue_Shortcode_Manager();

/* Add tweets shortcode to shortcode manager */
$av_sm->shortcodes['tweets'] = array(
	'label' 		=> __( 'Tweets', 'travelogue' ),
	'icon'			=> 'fa-twitter',
	'fields' 		=> array(
		'no' 	=> array(
				'label'		=> __( 'Number of tweets', 'travelogue' ),
				'type'		=> 'text',
				'default' 	=> '',
			),
		),
	);

/* Add recent posts shortcode to shortcode manager */


$av_sm->shortcodes['column'] = array(
	'label' 		=> __( 'Columns', 'travelogue' ),
	'icon'			=> 'fa-th-list',
	'fields' 		=> array(
		'width' 	=> array(
				'label'         => __( 'Width', 'travelogue' ),
				'type'	        => 'select',
				'options'	=> array(
								'' 	=> '',
								'1/2' 	=> __( 'One half', 'travelogue' ),
								'1/3' 	=> __( 'One third', 'travelogue' ),
								'1/4' 	=> __( 'One four', 'travelogue' ),
								'2/3' 	=> __( 'One third', 'travelogue' )
							),
			),
		),
	);


/* Add recent portfolios shortcode to shortcode manager */
$av_sm->shortcodes['dropcap'] = array(
	'label' 		=> __( 'Dropcap', 'travelogue' ),
	'icon'			=> 'fa-th-large',
	'fields' 		=> array(
		'content' 	=> array(
				'label' => __( 'Dropcap letter', 'travelogue' ),
				'type'	=> 'text',
			),
		'color' 	=> array(
				'label' 	=> __( 'Color', 'travelogue' ),
				'type'		=> 'select',
				'options'	=> array(
								''		=> '',
								'green' => __( 'Green', 'travelogue' ),
								'black' => __( 'Black', 'travelogue' )
							),
			),
		),
	);



/* Add recent portfolios shortcode to shortcode manager */
$av_sm->shortcodes['text_highlight'] = array(
	'label' 		=> __( 'Text highlight', 'travelogue' ),
	'icon'			=> 'fa-th-large',
	'fields' 		=> array(
		'content' 	=> array(
				'label' => __( 'Content', 'travelogue' ),
				'type'	=> 'textarea',
			),
		),
	);



/* Add call to action 1 shortcode to shortcode manager */
$av_sm->shortcodes['blockquote'] = array(
	'label' 		=> __( 'Blockquote', 'travelogue' ),
	'icon'			=> 'fa-info',
	'fields' 		=> array(
		'content' 	=> array(
				'label' => __( 'Blockquote content', 'travelogue' ),
				'type'	=> 'textarea',
			),
		),
	);




$av_sm->shortcodes['icon'] = array(
	'label' 		=> __( 'Icon', 'travelogue' ),
	'icon'			=> 'fa-th-list',
	'fields' 		=> array(
		'icon' 	=> array(
				'label'         => __( 'Icon', 'travelogue' ),
				'type'	        => 'select',
				'options'	=> $fa_icons
			),
		),
	);




/* Add recent portfolios shortcode to shortcode manager */
$av_sm->shortcodes['button'] = array(
	'label' 		=> __( 'Button', 'travelogue' ),
	'icon'			=> 'fa-th-large',
	'fields' 		=> array(
		'text' 	=> array(
				'label' => __( 'Button text', 'travelogue' ),
				'type'	=> 'text',
			),
		'url' 	=> array(
				'label' => __( 'Button link', 'travelogue' ),
				'type'	=> 'text',
			),
		'color' 	=> array(
				'label' 	=> __( 'Button color', 'travelogue' ),
				'type'		=> 'select',
				'options'	=> array(
								''	=> '',
								'white' => __( 'White', 'travelogue' ),
								'green' => __( 'Green', 'travelogue' ),
								'black' => __( 'Black', 'travelogue' )
							),
			),
		'size' 	=> array(
				'label' 	=> __( 'Size', 'travelogue' ),
				'type'		=> 'select',
				'options'	=> array(
								''		=> '',
								'button-small' 	=> __( 'Small', 'travelogue' ),
								'button-medium' => __( 'Medium', 'travelogue' ),
								'button-big' 	=> __( 'Big', 'travelogue' ),
							),
			),
		'style' 	=> array(
				'label' 	=> __( 'Style', 'travelogue' ),
				'type'		=> 'select',
				'options'	=> array(
								''		          => '',
								'button-v1'               => __( 'Button-v1', 'travelogue' ),
								'button-v1 radius-button' => __( 'Button-v1 radius-button', 'travelogue' ),
								'button-v2'               => __( 'Button-v2', 'travelogue' ),
								'button-v2 radius-button' => __( 'Button-v2 radius-button', 'travelogue' ),
							),
			),
		'dataeffect' 	=> array(
				'label' => __( 'Custom class', 'travelogue' ),
				'type'	=> 'text',
			),
		),
	);




/* Add recent portfolios shortcode to shortcode manager */
$av_sm->shortcodes['tabs'] = array(
	'label' 		=> __( 'Tabs', 'travelogue' ),
	'icon'			=> 'fa-th-large',
	'fields' 		=> array(
		'number_of_tabs' 	=> array(
				'label' 	=> __( 'Number of tabs to show', 'travelogue' ),
				'type'		=> 'select',
				'options'	=> array(
								''  => '',
								'2' => __( '2 tabs', 'travelogue' ),
								'3' => __( '3 tabs', 'travelogue' ),
								'4' => __( '4 tabs', 'travelogue' ),
								'5' => __( '5 tabs', 'travelogue' )
							),
			),
		'tab1_title' 	=> array(
				'label' => __( 'First tab title', 'travelogue' ),
				'type'	=> 'text',
			),
		'tab1_icon' 	=> array(
				'label' => __( 'First tab icon', 'travelogue' ),
				'type'	=> 'select',
				'options'	=> $fa_icons
			),
		'tab1_content' 	=> array(
				'label' => __( 'First tab content', 'travelogue' ),
				'type'	=> 'textarea',
			),
		'tab2_title' 	=> array(
				'label' => __( 'Second tab title', 'travelogue' ),
				'type'	=> 'text',
			),
		'tab2_icon' 	=> array(
				'label' => __( 'Second tab icon', 'travelogue' ),
				'type'	=> 'select',
				'options'	=> $fa_icons
			),
		'tab2_content' 	=> array(
				'label' => __( 'Second tab content', 'travelogue' ),
				'type'	=> 'textarea',
			),
		'tab3_title' 	=> array(
				'label' => __( 'Third tab title', 'travelogue' ),
				'type'	=> 'text',
			),
		'tab3_icon' 	=> array(
				'label' => __( 'Third tab icon', 'travelogue' ),
				'type'	=> 'select',
				'options'	=> $fa_icons
			),
		'tab3_content' 	=> array(
				'label' => __( 'Third tab content', 'travelogue' ),
				'type'	=> 'textarea',
			),
		'tab4_title' 	=> array(
				'label' => __( 'Fourth tab title', 'travelogue' ),
				'type'	=> 'text',
			),
		'tab4_icon' 	=> array(
				'label' => __( 'Fourth tab icon', 'travelogue' ),
				'type'	=> 'select',
				'options'	=> $fa_icons
			),
		'tab4_content' 	=> array(
				'label' => __( 'Fourth tab content', 'travelogue' ),
				'type'	=> 'textarea',
			),
		'tab5_title' 	=> array(
				'label' => __( 'Fifth tab title', 'travelogue' ),
				'type'	=> 'text',
			),
		'tab5_icon' 	=> array(
				'label' => __( 'Fifth tab icon', 'travelogue' ),
				'type'	=> 'select',
				'options'	=> $fa_icons
			),
		'tab5_content' 	=> array(
				'label' => __( 'Fifth tab content', 'travelogue' ),
				'type'	=> 'textarea',
			),


		),
	);




?>